# This is a basic workflow to help you get started with Actions
#
name: My-GitHubActions-Basics
env:
  APPLICATION_NAME: "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{ github.sha }}"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  my_testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
    - name: Execute fiew command
      run: |
        echo "Hello App 1"
        echo "Hello App 2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"   
     
    - name: List current folder
      run: ls -la
    
#    - name: Git clone my repo
#      uses: action/checkout@v1
    
    - name: List current folder
      run: ls -la
    
    - name: test our packages
      run: |
       aws --version
       zip --version
  
  my_deploy:      
    # From ADV
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
      VAR1: "This is job level 1"
      VAR2: "This is job level 2"
    
    steps:
      - name: Print_hello
        run: |
          echo "Hello world from my_testing_1"
          echo " Var1 = ${{ env.VAR1 }}"
          echo " Var1 = ${{ env.VAR2 }}"
          echo " Var3 = $LOCAL_VAR"
        env:
           LOCAL_VAR: "Superlocal"
           
    
      - name: Deployyment package
        run : echo "Deploy name is ${{ env.APPLICATION_NAME }}" 
        

  my_deploy_windows:      
    # From ADV 
    runs-on: windows-latest
    needs: [my_deploy] 
    steps:
    - name: Windows
#      run: dir
      run: C:\Program Files\PowerShell\7\pwsh.EXE
